server:
  port: 80

zuul:
  routes:
    cockpit:
      service-id: cockpit
      path: /admin/**
      url: http://localhost:9090/
    cockpit_internal:
      service-id: cockpit
      path: /cockpit/**
      url: http://localhost:9090/
  ssl-hostname-validation-enabled: false